# Generated by Django 3.1.3 on 2020-11-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='specs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepal_length', models.IntegerField(default=0)),
                ('sepal_width', models.IntegerField(default=0)),
                ('petal_length', models.IntegerField(default=0)),
                ('petal_width', models.IntegerField(default=0)),
            ],
        ),
    ]
